### ISSUE TITLE
fabric versiyon

### ISSUE THREAD

**Issue by Rogenar** [Minecraft-LightLand/L2Library#1]
When will the fabric version of this backpack mod come? There are too many backpack mods for the forge mod. I have a backpack problem in the fabric version.

**Comment by lcy0x1** [comment]
I started porting my library mod to Architectury, which is a Forge-Fabric bridge of mod development platform. Once I succeed, it will be available on fabric. Though a lot of my other mods are dependent on forge only

**Comment by lcy0x1** [comment]
It doesn't go well. My mod is dependent on Registrate, which differs too much on forge and on fabric. I need to find a way to use it in Architectury first.

**Comment by lcy0x1** [comment]
Also for mods depending on Curios, now I need to make it compat with Trinkets instead, which is an entirely different mod...
