### ISSUE TITLE
incompatible with Just Leveling

### ISSUE THREAD

**Issue by Acurid** [Minecraft-LightLand/L2Library#10]
L2's Attributes tab overlays with JL's Aptitudes tab.
Making it almost impossible to use both mods at the same time.

![Screenshot 2024-04-20 213044](https://github.com/Minecraft-LightLand/L2Library/assets/125478864/3b714652-c318-4f2a-9628-e1d8eeb9a745)

**Comment by lcy0x1** [comment]
I asked their dev if they want to cooperate on this, and got no reply.

Just Leveling is crashy as hell anyway. Use Passive Skill Tree as replacement.
