### ISSUE TITLE
l2library particle rendering crash with most likely starved stalker

### ISSUE THREAD

**Issue by loti1234** [Minecraft-LightLand/L2Library#11]
[crash-2024-06-19_02.07.52-client.txt](https://github.com/user-attachments/files/15893833/crash-2024-06-19_02.07.52-client.txt)

[latest.log](https://github.com/user-attachments/files/15893835/latest.log)

**Comment by lcy0x1** [comment]
Which mod is that? It’s a CME issue, which means it’s caused by some other mods modifying thing while I update the same thing. Are you able to reproduce this problem consistently?

**Comment by loti1234** [comment]
no not really i think
i think its kinda random

**Comment by lcy0x1** [comment]
That means it's a thread conflict. Something is trying to give mob effects in the wrong thread it seems

**Comment by lcy0x1** [comment]
please join discord and I can try to give you a debug jar and identify the root cause

**Comment by lcy0x1** [comment]
stale
