### ISSUE TITLE
[1.21.1] L2 Crash starting MC

### ISSUE THREAD

**Issue by Periam** [Minecraft-LightLand/L2Library#14]
After installing the latest mod version the game crashed

Attached the log 

[crash-2024-09-23_12.07.29-client.txt](https://github.com/user-attachments/files/17099759/crash-2024-09-23_12.07.29-client.txt)
[latest.log](https://github.com/user-attachments/files/17099760/latest.log)

**Comment by lcy0x1** [comment]
Looks like some problem with GregTech. Please open an issue there and I will discuss with their dev about how to solve it

**Comment by lcy0x1** [comment]
Wait no

**Comment by lcy0x1** [comment]
I saw the full problem now

**Comment by lcy0x1** [comment]
Are you able to reproduce this problem consistently?

**Comment by Periam** [comment]
yes. every time that I have the mods enable

**Comment by lcy0x1** [comment]
Since I cannot reproduce this issue, I'm relying you to tell my if my fixes are working or not. Would you like to join my discord? https://discord.gg/BCHNhsDMXz

**Comment by lcy0x1** [comment]
I already have a proposed fix

**Comment by Periam** [comment]
I will ping you on your discord. one minute

**Comment by lcy0x1** [comment]
fixed
