### ISSUE TITLE
[1.21.1] MC 1.21.1 l2tabs crash when opening inventory

### ISSUE THREAD

**Issue by Periam** [Minecraft-LightLand/L2Library#15]
After installing the latest version os L2 Library the game launched and the world loaded but when opening the inventory the game crashed.

[latest.log](https://github.com/user-attachments/files/17102650/latest.log)
[crash-2024-09-23_15.29.11-client.txt](https://github.com/user-attachments/files/17102655/crash-2024-09-23_15.29.11-client.txt)

**Comment by lcy0x1** [comment]
Addressed with new version of ModularGolem available in Discord for you to test. Same problem as last time but requires ModularGolem to do something as well

**Comment by lcy0x1** [comment]
fixed in ModularGolems 3.0.1+3
