### ISSUE TITLE
broken icon for l2 mods? neoforge 1.21.1 .65

### ISSUE THREAD

**Issue by VaporeonScripts** [Minecraft-LightLand/L2Library#16]
![image](https://github.com/user-attachments/assets/ab74a783-5a0c-44eb-af77-128034d0fe57)
https://mclo.gs/FXSBAwL

**Comment by lcy0x1** [comment]
I did not provide mod icon in jar. Maybe I should add them?

**Comment by VaporeonScripts** [comment]
probably ig?

**Comment by VaporeonScripts** [comment]
it prob says that cuz of no icons, so it thinks its broken
