### ISSUE TITLE
[1.12.1] [neoforge] crashes with accessories/curious compat layer

### ISSUE THREAD

**Issue by eternalbluepetya** [Minecraft-LightLand/L2Library#17]
im not really sure exactly whats happening, but [this issue from the accessories github](https://github.com/wisp-forest/accessories/issues/142) explains everything with logs and screenshots and such.

**Comment by lcy0x1** [comment]
I already fixed the problem in newest version of L2Library. Try to update and see if the issue with horizon persists

**Comment by lcy0x1** [comment]
Any feedback? Reach out to me in discord if you still have problems
