### ISSUE TITLE
Incompatibility with Accessories API

### ISSUE THREAD

**Issue by YuliaS11** [Minecraft-LightLand/L2Library#19]
[crash-2024-11-21_23.06.12-server.txt](https://github.com/user-attachments/files/17848420/crash-2024-11-21_23.06.12-server.txt)
There seems to be a serious problem causing various kind of crashes when used together with accessories mod and its curio compat layer. In this case, I was shot by a skeleton before the server crashed.

**Comment by lcy0x1** [comment]
Could you clarify which L2 mod is conflicting with accessories? I know Pandora certainly does but it’s not currently in your modlist.

From the crash log, it seems to be related to BiomeMakeOver?

**Comment by lcy0x1** [comment]
Stale. Discuss in discord if you have any question.
