### ISSUE TITLE
World corruption after killing a mob that has a potion effect

### ISSUE THREAD

**Issue by Jackiecrazy** [Minecraft-LightLand/L2Library#2]
There are many mods here, of course, but an instanceof check would be nice to prevent the occasional person who adds potions on the client side.
[crash-2023-05-05_08.26.21-client.txt](https://github.com/Minecraft-LightLand/L2Library/files/11402513/crash-2023-05-05_08.26.21-client.txt)

**Comment by lcy0x1** [comment]
What’s the version of L2Library? I remember fixing this issue some time ago because I also accidentally added potion on client side once

**Comment by lcy0x1** [comment]
Wait it is the newest version. I will post a fix ASAP

**Comment by lcy0x1** [comment]
fixed in 1.9.5
