### ISSUE TITLE
Curios gui

### ISSUE THREAD

**Issue by OneWorldStudio** [Minecraft-LightLand/L2Library#20]
![image](https://github.com/user-attachments/assets/fcb08da3-da82-4e5a-970f-35a8ee3e0829)
not works

**Comment by OneWorldStudio** [comment]
![image](https://github.com/user-attachments/assets/5ccca238-4135-4a54-a2bd-907a2a26510e)
not works

**Comment by OneWorldStudio** [comment]
There are no errors, there is no crash, there is no need in the logs, there is only Curios and l2 library

**Comment by lcy0x1** [comment]
As for the first image, it works as intended (only display in curios inventory menu, not in vanilla inventory menu)

As for the second image, please try if double quote works. If not, show me L2Library version and I will check

**Comment by OneWorldStudio** [comment]
> Что касается первого изображения, оно работает так, как и задумано (отображается только в меню инвентаря Curios, а не в меню инвентаря vanilla).
> 
> Что касается второго изображения, пожалуйста, попробуйте, работает ли двойная кавычка. Если нет, покажите мне версию L2Library, и я проверю

![image](https://github.com/user-attachments/assets/d2727459-853c-4ad7-a0b9-726054839dca)

**Comment by lcy0x1** [comment]
So now it works?

**Comment by OneWorldStudio** [comment]
> Так теперь это работает?
Yeah
