### ISSUE TITLE
Mouse tweaks(?) interaction

### ISSUE THREAD

**Issue by DaPuffer** [Minecraft-LightLand/L2Library#4]
Played 2 ftb modpacks:FTB:Unstable 1.20 and direwolf20 1.20. in both of them this mod is installed together with modular golems.
there is also Mouse tweaks. And if you sort the curios-like inventory tab, with a middle click or R,half of the items you have equipped just disappear. They don't drop,they don't get in your hand.  Just disappear

**Comment by lcy0x1** [comment]
Will check. I was using Curios mod’s own slot (same as scroll bar ones) for that page without changing anything, but since those slots are not sort-able in curios, there could be bugs both parties didn’t find out. Let me debug

**Comment by lcy0x1** [comment]
I don't think that's a feature in Mouse Tweaks. Could you find the mod responsible for sorting?

**Comment by lcy0x1** [comment]
I asked on Direwolf's discord and they said it doesn't cause items to disappear.
https://discord.com/channels/342506539296227329/788896883942096909/1164386190363992084
