### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Sephiroth91** [Minecraft-LightLand/L2Library#5]
Minecraft: 1.19.2
Forge: 43.3.0
Server crashes randomly.
[crash-2024-02-18_14.41.00-server.txt](https://github.com/Minecraft-LightLand/L2Library/files/14322682/crash-2024-02-18_14.41.00-server.txt)

**Comment by lcy0x1** [comment]
Update the mod. This issue has been fixed for a long time

**Comment by Sephiroth91** [comment]
Sure?
The log file says that the error comes from the library mod. However, I don't have this library in my modpack. But I have the Fruits Delight mod in the modpack and the library, if I saw it correctly, is integrated into this mod. Therefore I don't know how to update the library because fruits delight uses the last version of l2library that was integrated into the mod.

**Comment by lcy0x1** [comment]
Ah, I forgot to update it in Fruits Delight workspace. I will update it in next version. Anyway you should be able to fix it by installing L2Library separately. Your installation will take precedence over the the builtin library
