### ISSUE TITLE
This mod doesn't like when mods mess with the cap.

### ISSUE THREAD

**Issue by border999** [Minecraft-LightLand/L2Library#7]
https://gist.github.com/border999/1c6d10b98ba31065dfc98762310801aa

**Comment by lcy0x1** [comment]
It’s because the entity does not have a `level` (meaning the dimension they are in), but it’s expected in Minecraft. 

The problem is that the mod stats_and_skills adds a skeleton minion without dimension. I will ask them to fix the problem. At the same time, I will add a check as well.

**Comment by lcy0x1** [comment]
Okay for this use case I must have access to level. It’s not something I should fix on my end. Please report to Stats and Skills

**Comment by lcy0x1** [comment]
They are using GitLab. Please help me to report it first. I will setup GitLab later

**Comment by lcy0x1** [comment]
Also please join discord for further discussions. I check discord much more regularly
