### ISSUE TITLE
L2 Tabs Curios Tab not working on latest version.

### ISSUE THREAD

**Issue by Atticool** [Minecraft-LightLand/L2Library#9]
OS: MacOS

Installed Mods:
artifacts-forge-9.4.2
architectury-9.2.14-forge
cloth-config-11.1.118-forge
curios-forge-5.8.1+1.20.1
l2library-2.4.24

Tested on a fresh Minecraft Instance.
I have also tested this with the latest version of L2Artifacts and found the same issue.

After opening the inventory and clicking on the Curios Tab, the inventory does not open, and the hover text stays on the cursor until I close my inventory.

https://github.com/Minecraft-LightLand/L2Library/assets/35721034/5e2dd7eb-f10f-42ff-8623-2a31e2a4e9c7

There wasn't any errored log output, but I've attached it anyway:
https://pastebin.com/7nkNyEBS

**Comment by Atticool** [comment]
just saw on the discord to downgrade to curios 5.7.2 – this works

**Comment by lcy0x1** [comment]
fixed in 2.4.25
